const S=[
{id:"01",title:"Silent Grid",tag:"COMMUNICATIONS",desc:"The network goes quiet while physical systems keep running.",res:76,pressure:42,exposure:58,recovery:"6 cycles",nodes:[["Energy","stable",91,"reserve margin"],["Cooling","stable",84,"thermal headroom"],["Comms","critical",28,"signal continuity"],["Navigation","stress",61,"position confidence"],["Operations","stress",67,"operator load"],["Containment","stable",88,"isolation margin"]],trace:[["00:00","Signal coherence drops","communications","CRITICAL"],["00:18","Navigation enters degraded mode","dependency bridge","WARN"],["00:42","Operator load rises","human interface","WARN"],["01:20","Local autonomy stabilizes grid","recovery layer","RECOVER"]],insight:"The network is not the only thing that fails when communication disappears.",recs:["Prioritize local autonomy","Reduce cross-system chatter","Preserve navigation confidence"]},
{id:"02",title:"Redline Cooling",tag:"THERMAL LOAD",desc:"A cooling loop loses capacity just as the grid enters peak demand.",res:61,pressure:71,exposure:73,recovery:"9 cycles",nodes:[["Energy","stress",68,"peak demand"],["Cooling","critical",22,"thermal headroom"],["Comms","stable",88,"signal continuity"],["Navigation","stable",90,"position confidence"],["Operations","stress",55,"operator load"],["Containment","stress",64,"isolation margin"]],trace:[["00:00","Cooling capacity falls below reserve","thermal loop","CRITICAL"],["00:25","Energy demand spikes","load coupling","WARN"],["00:51","Operations throttles non-essential load","control layer","WARN"],["01:44","Thermal margin returns","recovery layer","RECOVER"]],insight:"Peak demand turns a local cooling problem into a systems problem.",recs:["Throttle non-critical loads","Protect thermal reserve","Avoid recovery oscillation"]},
{id:"03",title:"Doomsday",tag:"MULTI-FAULT",desc:"Two independent faults arrive before the first has finished recovering.",res:38,pressure:89,exposure:92,recovery:"14 cycles",nodes:[["Energy","critical",31,"reserve margin"],["Cooling","critical",36,"thermal headroom"],["Comms","stress",57,"signal continuity"],["Navigation","stress",49,"position confidence"],["Operations","critical",34,"operator load"],["Containment","stress",52,"isolation margin"]],trace:[["00:00","Primary fault detected","initiating event","CRITICAL"],["00:31","Recovery begins too early","timing debt","WARN"],["01:03","Second fault compounds pressure","cascade bridge","CRITICAL"],["02:10","Containment priority activates","survival layer","CRITICAL"],["04:30","Recovery window opens","stabilization","RECOVER"]],insight:"The dangerous moment is starting recovery while the system is still accumulating debt.",recs:["Stabilize before optimizing","Protect recovery resources","Break dependency loops first"]},
{id:"04",title:"Workshop Ghost",tag:"HUMAN FACTOR",desc:"Machines remain healthy, but the decision layer becomes overloaded.",res:83,pressure:49,exposure:44,recovery:"4 cycles",nodes:[["Energy","stable",94,"reserve margin"],["Cooling","stable",92,"thermal headroom"],["Comms","stable",82,"signal continuity"],["Navigation","stress",63,"position confidence"],["Operations","critical",29,"operator load"],["Containment","stable",90,"isolation margin"]],trace:[["00:00","Alert volume exceeds operator budget","human layer","WARN"],["00:22","Duplicate decisions appear","coordination","WARN"],["00:48","Automation absorbs routine work","support layer","RECOVER"],["01:12","Operator attention returns","human layer","RECOVER"]],insight:"A resilient machine can still produce a fragile system if the human decision layer becomes the bottleneck.",recs:["Compress alert volume","Automate routine decisions","Keep humans on high-value decisions"]}
];
let selected=null; const $=id=>document.getElementById(id);
function scenarios(){ $("scenarios").innerHTML=S.map(x=>`<div class="scenario ${selected?.id===x.id?"active":""}" data-id="${x.id}"><span class="num">${x.id}</span><h3>${x.title}</h3><p>${x.desc}</p><span class="chip">${x.tag}</span></div>`).join("");document.querySelectorAll(".scenario").forEach(e=>e.onclick=()=>select(e.dataset.id))}
function select(id){selected=S.find(x=>x.id===id);scenarios();$("title").textContent=selected.title;$("desc").textContent=selected.desc;$("run").disabled=false;$("state").textContent="READY TO RUN";$("insight").innerHTML=`<b>◌</b><h3>Pressure profile loaded.</h3><p>${selected.insight}</p>`}
function nodes(data,animate=true){$("nodes").innerHTML=data.map(n=>`<div class="node"><div class="nodehead"><span class="nodename">${n[0]}</span><span class="status ${n[1]}">${n[1].toUpperCase()}</span></div><div class="bar ${n[1]}"><i style="width:${animate?0:n[2]}%"></i></div><small>${n[2]}% · ${n[3]}</small></div>`).join("");if(animate)setTimeout(()=>document.querySelectorAll(".bar i").forEach((e,i)=>e.style.width=data[i][2]+"%"),40)}
function trace(data){$("trace").innerHTML=data.map(x=>`<div class="row"><time>${x[0]}</time><span class="event">${x[1]}<small>${x[2]}</small></span><span class="level">${x[3]}</span></div>`).join("")}
function run(){if(!selected)return;$("run").disabled=true;$("state").textContent="SIMULATION RUNNING";nodes(selected.nodes,true);$("trace").innerHTML='<div class="empty">Replaying dependency chain…</div>';$("insight").innerHTML='<div class="insight"><b>◌</b><h3>Tracing the cascade.</h3><p>Following fictional dependency edges through the Sentinel Grid.</p></div>';[["res",selected.res],["pressure",selected.pressure],["exposure",selected.exposure]].forEach((x,i)=>setTimeout(()=>$(x[0]).textContent=x[1]+"%",250+i*220));setTimeout(()=>{$("meter").style.width=selected.res+"%";$("resLabel").textContent=selected.res>75?"comfortable margin":selected.res>50?"watch interacting stress":"recovery priority";$("recovery").textContent=selected.recovery;trace(selected.trace);$("state").textContent="TRACE COMPLETE";$("insight").innerHTML=`<b>◎</b><h3>${selected.insight}</h3><div class="recovery">${selected.recs.map(x=>`<div>${x}</div>`).join("")}</div>`;$("run").disabled=false},1100)}
$("run").onclick=run;scenarios();nodes([["Energy","stable",88,"reserve margin"],["Cooling","stable",86,"thermal headroom"],["Comms","stable",92,"signal continuity"],["Navigation","stable",90,"position confidence"],["Operations","stable",85,"operator load"],["Containment","stable",89,"isolation margin"]],false);
